sena/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from rest_framework.documentation import include_docs_urls
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'categoria', views.CategoriaViewSet)
router.register(r'producto', views.ProductoViewSet)
router.register(r'usuario', views.UsuarioViewSet)
router.register(r'categoria-etiqueta', views.CategoriaEtiquetaViewSet)
router.register(r'subcategoria-etiqueta', views.SubCategoriaEtiquetaViewSet)
router.register(r'producto-subcategoria', views.ProductoSubCategoriaViewSet)
router.register(r'venta', views.VentaViewSet)
router.register(r'detalle-venta', views.DetalleVentaViewSet)
#router.register(r'registrar-usuario', views.DetalleVentaViewSet)
router.register(r'comentarios', views.ComentariosViewSet)

urlpatterns = [
	path('index/', views.index, name="index"),
	path('', views.inicio, name="inicio"),
    
	#API
    path('api/1.0/', include(router.urls)),
    path('api/1.0/token-auth/', views.CustomAuthToken.as_view()),
	path('api/1.0/api-auth/', include('rest_framework.urls')),

	# Autenticación de usuarios del sistema
	path('login/', views.login, name="login"),
	path('logout/', views.logout, name="logout"),
	path('registrar_usuario/', views.registrar_usuario, name="registrar_usuario"),
    path("recuperar_clave/", views.recuperar_clave, name="recuperar_clave"),
	path("verificar_recuperar/", views.verificar_recuperar, name="verificar_recuperar"),
 
 	# Usuarios CRUD
	path("usuarios_listar/", views.usuarios, name="usuarios_listar"),
	path("usuarios_form/", views.usuarios_form, name="usuarios_form"),
	path("usuarios_eliminar/<int:id>", views.usuarios_eliminar, name="usuarios_eliminar"),
	path("usuarios_formulario_editar/<int:id>", views.usuarios_formulario_editar, name="usuarios_formulario_editar"),
	path("usuarios_actualizar/", views.usuarios_actualizar, name="usuarios_actualizar"),
    path('edite_profile',views.editeUser,name='edite_profile'),
	
	# CRUD de Categorías
	path("categorias_listar/", views.categorias, name="categorias_listar"),
	path("categorias_form/", views.categorias_form, name="categorias_form"),
	path("categorias_crear/", views.categorias_crear, name="categorias_crear"),
	path("categorias_eliminar/<int:id>", views.categorias_eliminar, name="categorias_eliminar"),
	path("categorias_formulario_editar/<int:id>", views.categorias_formulario_editar, name="categorias_formulario_editar"),
	path("categorias_actualizar/", views.categorias_actualizar, name="categorias_actualizar"),

	# CRUD de Productos
	path("productos_listar/", views.productos, name="productos_listar"),
	path("productos_form/", views.productos_form, name="productos_form"),
	path("productos_crear/", views.productos_crear, name="productos_crear"),
	path("productos_eliminar/<int:id>", views.productos_eliminar, name="productos_eliminar"),
	path("productos_formulario_editar/<int:id>", views.productos_formulario_editar, name="productos_formulario_editar"),
	path("productos_actualizar/", views.productos_actualizar, name="productos_actualizar"),

	path("ver_perfil/", views.ver_perfil, name="ver_perfil"),
	path("cc_formulario/", views.cambio_clave_formulario, name="cc_formulario"),
	path("cambiar_clave/", views.cambiar_clave, name="cambiar_clave"),
 
	# CRUD de Devoluciones
	path("devoluciones/", views.devoluciones, name="devoluciones"),
	path("devoluciones_form/", views.devoluciones_form, name="devoluciones_form"),
	path("devoluciones_crear/", views.devoluciones_crear, name="devoluciones_crear"),
	path("devoluciones_formulario_editar/<int:id>", views.devoluciones_formulario_editar, name="devoluciones_formulario_editar"),
	path("devoluciones_actualizar/", views.devoluciones_actualizar, name="devoluciones_actualizar"),
	path("devoluciones_eliminar/<int:id>", views.devoluciones_eliminar, name="devoluciones_eliminar"),

    path('cargar/', views.cargar_image, name='cargar_image'),

	# carrito de compra
	path("carrito_add/", views.carrito_add, name="carrito_add"),
	path("visualizar_carrito/", views.visualizar_carrito, name="visualizar_carrito"),
	path("ver_carrito/", views.ver_carrito, name="ver_carrito"),
	path("vaciar_carrito/", views.vaciar_carrito, name="vaciar_carrito"),
	path("eliminar_item_carrito/<int:id_producto>", views.eliminar_item_carrito, name="eliminar_item_carrito"),
    path("eliminar_item_carrito_ver/<int:id_producto>", views.eliminar_item_carrito_ver, name="eliminar_item_carrito_ver"),
	path("actualizar_totales_carrito/<int:id_producto>/", views.actualizar_totales_carrito, name="actualizar_totales_carrito"),
    path("actualizar_totales_carrito_ver/<int:id_producto>/", views.actualizar_totales_carrito_ver, name="actualizar_totales_carrito_ver"),
 
	#ventas
	path("realizar_venta/", views.realizar_venta, name="realizar_venta"),
    path("ventas_ver/", views.ventas_ver, name="ventas_ver"),
	path("eliminar_venta/<int:id_venta>", views.eliminar_venta, name="eliminar_venta"),
	path("prueba_correo/", views.prueba_correo, name="prueba_correo"),
	path("estado_venta/<int:id>/", views.estado_venta, name="estado_venta"),
	path('lista_pedidos/', views.lista_pedidos, name='lista_pedidos'),

	#etiquetas
    path("etiquetas_listar/", views.etiquetas_listar, name="etiquetas_listar"),
    path("etiquetas_crear/", views.etiquetas_crear, name="etiquetas_crear"),
    path("etiquetas_eliminar/<int:id>", views.etiquetas_eliminar, name="etiquetas_eliminar"),
    path("etiquetas_form_editar/<int:id>", views.etiquetas_formulario_editar, name="etiquetas_form_editar"),
    path("etiquetas_actualizar", views.etiquetas_actualizar, name="etiquetas_actualizar"),
    path("etiquetas_form/", views.etiquetas_form, name="etiquetas_form"),

	#Terminos y condiciones
 	path("term_y_cond/", views.term_y_cond, name="term_y_cond"),

    # Comentarios
    path('comentarios_listar/', views.comentarios_listar, name='comentarios_listar'),
    path("comentarios_form/", views.comentarios_form, name="comentarios_form"),
    path("comentarios_crear/", views.comentarios_crear, name="comentarios_crear"),
    path("comentarios_actualizar/", views.comentarios_actualizar, name="comentarios_actualizar"),
    path('comentarios_eliminar/<int:id>/', views.comentarios_eliminar, name='comentarios_eliminar'),
    path("comentarios_editar/<int:id>", views.comentarios_editar, name="comentarios_editar"),
    path("comentarios_like/<int:id>/", views.comentarios_like, name='comentarios_like'),

	# tallas
	path("tallas_listar/", views.tallas_listar, name="tallas_listar"),
	path("talla_form/", views.tallas_form, name="tallas_form"),
	path("tallas_crear/", views.tallas_crear, name="tallas_crear"),
	path("tallas_actualizar/", views.tallas_actualizar, name="tallas_actualizar"),
	path("tallas_eliminar/<int:id>", views.tallas_eliminar, name="tallas_eliminar"),
 	path("tallas_editar/<int:id>", views.tallas_editar, name="tallas_editar"),
     
	#Trabaja con nosotros
 	path("trabaja_nosotros/", views.trabaja_nosotros, name="trabaja_nosotros"),

	#Pedidos y devoluciones
	path('mis_pedidos/', views.ver_pedidos_cliente, name='mis_pedidos'),
	path('cancelar_pedido/<int:pedido_id>/', views.cancelar_pedido, name='cancelar_pedido'),
    path('admin_pedidos/', views.lista_usuarios, name="lista_usuarios"),
    path('usuarios/<int:usuario_id>/pedidos/', views.ver_pedidos_usuario, name="ver_pedidos_usuario"),
    path('pedidos/<int:pedido_id>/cambiar_estado/', views.cambiar_estado_pedido, name='cambiar_estado_pedido'),
    
    path('pedido/<int:pedido_id>/apelar/', views.apelar_devolucion, name="apelar_devolucion"),
    path('mis_devoluciones/', views.ver_mis_devoluciones, name='ver_mis_devoluciones'),
    path('devoluciones_admin/', views.listar_devoluciones, name='listar_devoluciones'),
    path('devoluciones/<int:devolucion_id>/cambiar_estado/', views.cambiar_estado_devolucion, name='cambiar_estado_devolucion'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/models.py
from django.contrib.auth.models import AbstractUser
from .authentication import CustomUserManager
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


# Create your models here.

class Usuario(AbstractUser):
	username = None
	nombre = models.CharField(max_length=254)
	email = models.EmailField(max_length=254, unique=True)
	image = models.ImageField(upload_to='edite_profile', null=True, blank=True)
	ROLES = (
		(1, "Administrador"),
		(2, "Despachador"),
		(3, "Cliente"),
	)
	rol = models.IntegerField(choices=ROLES, default=3)
	foto = models.ImageField(upload_to="fotos/", default="fotos/default.png", blank=True)
	token_recuperar = models.CharField(max_length=254, default="", blank=True, null=True)
	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ["nombre"]
	objects = CustomUserManager()

	def __str__(self):
		return self.nombre

class Categoria(models.Model):
	nombre = models.CharField(max_length=254)
	descripcion = models.TextField()
 

	def __str__(self):
		return self.nombre


class CategoriaEtiqueta(models.Model):
	nombre = models.CharField(max_length=254, unique=True)

	def __str__(self):
		return self.nombre
	
class SubCategoriaEtiqueta(models.Model):
	nombre = models.CharField(max_length=254)
	id_categoria_etiqueta = models.ForeignKey(CategoriaEtiqueta, on_delete=models.DO_NOTHING)

	def __str__(self):
		return self.nombre
	

class Producto(models.Model):
	nombre = models.CharField(max_length=254)
	informacion = models.CharField(max_length=254)
	precio = models.IntegerField()
	inventario = models.IntegerField()
	fecha_creacion = models.DateField()
	categoria = models.ForeignKey(CategoriaEtiqueta,on_delete=models.DO_NOTHING)
	foto = models.ImageField(upload_to="fotos_productos/", default="fotos_productos/default.png")

	def __str__(self):
		return self.nombre


class ProductoSubCategoria(models.Model):
	id_producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
	id_sub_categoria_etiqueta = models.ForeignKey(SubCategoriaEtiqueta, on_delete=models.DO_NOTHING)

	def __str__(self):
		return f'{self.id_producto}, {self.id_sub_categoria_etiqueta}'

class Venta(models.Model):
	fecha_venta = models.DateTimeField(auto_now=True)
	usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
	ESTADOS = (
		(1, 'Pendiente'),
		(2, 'Pagada'),
		(3, 'Rechazada'),
		(4, 'Enviado'),
	)
	estado = models.IntegerField(choices=ESTADOS, default=1)
	motivo_rechazo = models.TextField(blank=True, null=True)

	def __str__(self):
		return f"{self.id} - {self.usuario}"


class DetalleVenta(models.Model):
	venta = models.ForeignKey(Venta, on_delete=models.DO_NOTHING)
	producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
	cantidad = models.IntegerField()
	precio_historico = models.IntegerField()
	id_usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)

	def __str__(self):
		
		return f"{self.id} - {self.venta}"


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

class Devolucion(models.Model):
    pedido = models.ForeignKey(Venta, on_delete=models.CASCADE, related_name="devoluciones")
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    motivo = models.TextField()
    fecha_devolucion = models.DateTimeField(auto_now_add=True)
    foto = models.ImageField(upload_to='devoluciones_fotos/', blank=True, null=True)
    ESTADOS = (
        (1, 'Enviada'),
        (2, 'Aceptada'),
        (3, 'Rechazada'),
    )
    estado = models.IntegerField(choices=ESTADOS, default=1)  # Estado por defecto es 'Enviada'
    
    # Método para obtener el estado en texto
    def estado_texto(self):
        return dict(self.ESTADOS).get(self.estado, 'Desconocido')

    def __str__(self):
        return f"Devolución para Pedido #{self.pedido.id} - Usuario: {self.usuario.username}"
    
	
class Comentarios(models.Model):
    comentarios = models.TextField()
    descripcion = models.TextField()
    fecha_creacion = models.DateField(null=True, blank=True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.comentarios


class CarouselItem(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    imagen = models.ImageField(upload_to='carousel/')
    

    def __str__(self):
        return self.titulo   
	
class Tallas(models.Model):    
	talla = models.CharField(max_length=254)
 
	def __str__(self):
    		return self.talla
	
class ProductoTallas(models.Model):
	id_producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
	id_talla = models.ForeignKey(Tallas, on_delete=models.DO_NOTHING)
 
	def __str__(self):
    		return self.nombre

tienda/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

tienda/templates/tienda/login/cambio_clave.html
{% extends 'tienda/inicio/base.html' %}
{% load static %}

{% block titulo %}Inicio{% endblock %}

{% block contenedor %}
<div style="display: flex; justify-content: center; align-items: center; height: 90vh;">

    <div style="border: 2px solid; width: 100%; max-width: 700px; padding: 20px; box-shadow: 0 0 10px rgba(0,0,0,0.1);">

        <h1 class="titul" style="text-align: center;">Cambiar contraseña</h1>
        <form action="{% url 'cambiar_clave' %}" method="post" class="mb-3 mt-5 w-100 h-100 ml-0 mr-0 mx-auto" style="max-width: 540px;">
            {% csrf_token %}

            <label class="form-control" style="border: 2px solid; padding: 10px; border-radius: 4px;">Contraseña actual</label>
            <input type="password" name="clave" required="" autofocus="" class="form-control"><br><br>

            <label class="form-control" style="border: 2px solid; padding: 10px; border-radius: 4px;">Contraseña nueva</label>
            <input type="password" name="nueva1" required="" class="form-control"><br>
            
            <label class="form-control" style="border: 2px solid; padding: 10px; border-radius: 4px;">Repetir Contraseña</label>
            <input type="password" name="nueva2" required="" class="form-control"><br>

            <div style="text-align: center;">
                <button type="submit" class="btn btn-success">Guardar</button>
            </div>          </form>
    </div>
</div>

{% endblock %}

tienda/templates/tienda/login/login.html
{% load static %}
{% load humanize %}
{% block estilos %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'tienda/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'tienda/css/login.css' %}" />
    <link rel="stylesheet" href="{% static 'tienda/css/iniciarSesion.css' %}" />

</head>
{% endblock %}



{% block contenedor %}

<section id="cuadroLogin">
    <div class="cuadroLogin">
        <form action="{% url 'login' %}" method="post" class="m-3 text-center">
            
        </form>
    </div>
</section>



{% endblock %}


<!--<div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
                <div class="card h-100">
                    <img src="{{ p.foto.url }}" class="card-img-top" alt="{{ p.nombre }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ p.nombre }}</h5>
                        <p class="card-text">
                            Precio: {{ p.precio }}<br>
                            Existencias: {{ p.inventario }}<br>
                        </p>
                    </div>
                    <div class="card-footer">
                        <small class="text-body-secondary">{{ p.categoria }}</small>
                    </div>
                </div>
            </div>
        </div>-->

tienda/templates/tienda/login/perfil.html
{% extends 'tienda/inicio/base.html' %}
{% load static %}

{% block titulo %}Inicio{% endblock %}

{% block estilos %}
<link rel="stylesheet" href="{% static 'tienda/css/perfil.css' %}">
{% endblock %}

{% block contenedor %}
<br>
    <h1 class="titul" style="text-align: center;">Perfil</h1>
    <div id="card" class="card mb-3 mt-5 w-100 h-100 ml-0 mr-0 mx-auto" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ data.foto.url }}" class="img-fluid rounded-start" alt="..." onerror="this.style.display='none';">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ data.nombre }}</h5>
                    <p class="card-text">
                        Correo: {{ data.email }}<br/>
                        Rol: {{ data.get_rol_display }}<br/>
                    </p>
                    <p class="card-text">
                        <small class="text-body-secondary">
                            Id de usuario: {{ data.id }}
                        </small>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <br>
    <button id="editar" style="width: 120px; margin-left: 900px;" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Editar Perfil
    </button>
    <br>
    
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Edita tu perfil</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div style="display: flex; justify-content: center; align-items: center; height: 60vh;">

                    <div style="width: 100%; max-width: 700px; padding: 30px; box-shadow: 0 0 10px rgba(0,0,0,0.1);">
                
                        <h1 class="titul" style="text-align: center;">Editar Perfil ({{ data.id }})</h1>
                        <form action="{% url 'edite_profile' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ data.id }}">
                            <label class="form-control" style="border: 2px solid; padding: 10px; border-radius: 4px;">Nombre</label>
                            <input class="form-control" type="text" name="nombre" value="{{ data.nombre }}" /><br>
                
                            <label class="form-control" style="border: 2px solid; padding: 10px; border-radius: 4px;">Correo</label>
                            <input class="form-control" type="text" name="email" value="{{ data.email }}" /><br>
                            
                            <label class="form-control" style="border: 2px solid; padding: 10px; border-radius: 4px;">Cargar Imagen</label>
                            <input class="form-control" type="file" name="image" />

                            <br>
                            <div style="text-align: center;">
                                <button type="submit" class="btn btn-success">Actualizar</button>
                            </div> 
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                          
        </div>
        </div>
        </div>
    </div>
{% endblock %}

tienda/templates/tienda/login/recuperar.html
{% extends 'tienda/inicio/base.html' %}
{% load static %}

{% block titulo %}Login{% endblock %}

{% block contenedor %}

<form action="{% url 'recuperar_clave' %}" method="post" class="col-3 m-auto mt-5">
    <h3>Ingrese su correo</h3>
    {% csrf_token %}
    <input type="email" name="correo" class="form-control" placeholder="Correo" required=""><br>
    <button type="submit" class="btn btn-info">Recuperar...</button>
</form>

{% endblock %}

tienda/templates/tienda/login/registro.html
{% extends 'tienda/inicio/base.html' %}
{% load static %}

{% block titulo %}registro{% endblock %}

{% block contenedor %}

<form action="{% url 'registrar_usuario' %}" method="post" class="col-3 m-auto mt-5">
    <h3>Complete el formulario</h3>
    {% csrf_token %}
    <input type="text" name="nombre" class="form-control" placeholder="Nombre" required=""><br>
    <input type="email" name="correo" class="form-control" placeholder="Correo" required=""><br>
    <input type="password" name="clave1" class="form-control" placeholder="Contraseña" required=""><br>
    <input type="password" name="clave2" class="form-control" placeholder="Repita Contraseña" required=""><br>
    <button type="submit" class="btn btn-info">Registrarse</button>
</form>

{% endblock %}

tienda/templates/tienda/login/verificar_recuperar.html
{% extends 'tienda/inicio/base2.html' %}
{% load static %}

{% block titulo %}Login{% endblock %}

{% block contenedor %}

{% if check %}
    <form action="{% url 'verificar_recuperar' %}" method="post" class="mb-3 mt-5 w-100 h-100 ml-0 mr-0 mx-auto" style="max-width: 540px;">
        {% csrf_token %}
        <input type="hidden" name="check" value="{{ check }}"/>
        <input type="hidden" name="correo" class="form-control" placeholder="Correo" required="" value="{{correo}}"><br>
        <label>Contraseña nueva</label>
        <input type="password" name="nueva1" required="" class="form-control"><br>
        <label>Repetir Contraseña</label>
        <input type="password" name="nueva2" required="" class="form-control"><br>

        <button type="submit" class="btn btn-info">Guardar</button>
    </form>
{% else %}
    <form action="{% url 'verificar_recuperar' %}" method="post" class="col-3 m-auto mt-5">
        <h3>Ingrese el token enviado al correo</h3>
        {% csrf_token %}
        <input type="hidden" name="correo" class="form-control" placeholder="Correo" required="" value="{{correo}}"><br>
        <input type="text" name="token" class="form-control" placeholder="Token" required=""><br>
        <button type="submit" class="btn btn-info">Verificar...</button>
    </form>
{% endif %}

{% endblock %}